export const domainsList = [
    "Artificial Intelligence (AI)",
    "Machine Learning (ML)",
    "Data Science",
    "Cybersecurity",
    "Internet of Things (IoT)",
    "Cloud Computing",
    "Software Engineering",
    "Web Development",
    "Mobile App Development",
    "Blockchain Technology",
    "Power Systems",
    "Control Systems",
    "Signal Processing",
    "Telecommunications",
    "Robotics",
    "VLSI Design",
    "Automotive Engineering",
    "Aerospace Engineering",
    "Mechatronics",
    "Biomedical Engineering",
    "Manufacturing Engineering",
    "Structural Engineering",
    "Geotechnical Engineering",
    "Water Resources Engineering",
    "Environmental Engineering",
    "Transportation Engineering",
    "Process Engineering",
    "Biotechnology",
    "Materials Science and Engineering",
    "Computer Vision",
    "Natural Language Processing (NLP)",
    "Virtual Reality (VR)",
    "Augmented Reality (AR)",
    "Human-Computer Interaction (HCI)",
    "Game Development",
    "Bioinformatics",
    "Nanotechnology",
    "Renewable Energy",
    "Sustainable Development",
    "Smart Cities",
    "Robotics Process Automation (RPA)",
    "DevOps",
    "Data Engineering",
    "Data Analytics",
    "Business Intelligence (BI)",
    "Cyber Forensics",
    "Network Security",
    "Ethical Hacking",
    "Digital Forensics",
    "Information Security",
    "Quantum Computing",
    "Neural Networks",
    "Deep Learning",
    "Computer Graphics",
    "Computer Networks",
    "Operating Systems",
    "Database Management Systems (DBMS)",
    "Programming Languages (Python, Java, C++, etc.)",
    "Front-End Development",
    "Back-End Development",
    "Full-Stack Development",
    "User Experience (UX) Design",
    "User Interface (UI) Design",
    "Product Design",
    "Interaction Design",
    "Information Architecture",
    "Content Strategy",
    "Digital Marketing",
    "Social Media Marketing",
    "Search Engine Optimization (SEO)",
    "E-commerce",
    "Mobile Marketing",
    "Data Visualization",
    "Data Journalism",
    "Data Storytelling",
    "Data Ethics",
    "AI Ethics",
    "Machine Learning Ethics",
    "Algorithmic Bias",
    "Privacy",
    "Security",
    "Sustainability",
    "Social Impact",
    "Equity",
    "Inclusion",
    "Diversity",
    "Accessibility",
    "Human-Centered Design",
    "Design Thinking",
    "Agile Methodology",
    "Scrum",
    "Kanban",
    "Lean",
    "Project Management",
    "Product Management",
    "Business Analysis",
    "Systems Analysis",
    "Requirements Engineering",
    "Quality Assurance (QA)",
    "Testing",
];